// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21

// Console related
#define SYS_clrscr       22
#define SYS_setcursor    23
#define SYS_getcursor    24
#define SYS_setconsbuf   25
#define SYS_scrputc      26
#define SYS_curmove      27
#define SYS_getcch       28
#define SYS_pushword     29
#define SYS_putchar      30
#define SYS_savescr      31
#define SYS_restorescr   32
#define SYS_mirrorctx    33
#define SYS_setline      34
#define SYS_getline      35
#define SYS_deletech     36
#define SYS_getinput     37
